MT#55283 improve build test error output
Change-Id: I66ad3dbb1d746ad81d55c4daf922f0cfaf6f7850
(cherry picked from commit d851706c236f7fcb846b63c84c052c4e4adacd51)
(cherry picked from commit 2f99bbe48ce8b0bc1ba393c65ad240d5fde8c179)

diff --git a/utils/build_test_wrapper b/utils/build_test_wrapper
--- a/utils/build_test_wrapper
+++ b/utils/build_test_wrapper
@@ -7,13 +7,24 @@ if test "$MAKE" = ""; then
 fi
 echo "Looking for usable alternative for $TARGET"
 rm -f "$ROOT"-test
+rm -f .stderr.$$
 for x in "$ROOT"*.h; do
 	echo "Trying build with $x"
 	rm -f "$TARGET"
 	(echo '/******** GENERATED FILE ********/'; cat "$x") > "$TARGET"
-	$MAKE "$ROOT"-test && break
+	$MAKE "$ROOT"-test 2>> .stderr.$$ && break
 	echo "Failed build with $x"
 	rm -f "$TARGET"
 done
 rm -f "$ROOT"-test
-test -f "$TARGET"
+if test -f "$TARGET"; then
+	rm -f .stderr.$$
+	exit 0
+fi
+echo "Failed to find usable build alternative for $TARGET"
+echo "Collected stderr:"
+echo "--------------------------"
+cat .stderr.$$
+rm -f .stderr.$$
+echo "--------------------------"
+exit 1
